sudo: required

language: clojure
jdk:
  - oraclejdk8

services:
  - docker

env:
  global:
      - AWS_ACCESS_KEY_ID=xxxxxxxxxxxx
      - AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxx
      - AWS_CBOR_DISABLE=1

before_install:
  - docker-compose up -d

script:
  - lein test