sudo: required

language: clojure
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull adtile/kinesalite:latest
  - docker run -d -p 4567:4567 adtile/kinesalite:latest

script:
  - AWS_CBOR_DISABLE=1 lein test