version: "3.8"
services:
  lib:
    build: .
    volumes:
      - .:/code
      - ~/.m2:/root/.m2
    environment:
      - AWS_CBOR_DISABLE=1
      - AWS_ACCESS_KEY_ID=circleci
      - AWS_SECRET_KEY=circleci

    depends_on:
       - kinesis

  kinesis:
    image: adtile/kinesalite:latest
    ports:
      - 4567:4567
